name: Deploy Flask App

on:
  push:
    branches:
      - main  # Change this if you're using a different branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH into Server & Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/janak/Documents/My_Flask_App/Flask_CI_CD
            git pull origin main
            source venv/bin/activate
            pip install -r requirements.txt
            systemctl restart flaskapp
